print('25th July')
print('Dear Puneeth,')
print('             ')
print('     I am feeling very proud')
print('     I want to get a good data analyst job')
print('     This is where you started')
print('                            ')
print('Signing off')
print('Puneeth')